GET http://localhost:4000/user/list
###
POST http://localhost:4000/user/login
Content-Type: application/json

{
    "email":"mohsin1@gmail.com",
    "password":"123123123"
}
###
POST http://localhost:4000/user/create
Content-Type: application/json

{
    "email":"mohsin11@gmail.com",
    "password":"123123123",
    "displayName":"Ali Ali"
}
###
POST http://localhost:4000/image
Content-Type: application/x-www-form-urlencoded

{
    "avatar":"‪C:\Users\kkc\Downloads\Blogs2_cropped.png"
}
